apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nodejs-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      role: nodejs-k8s
  template:
    metadata:
      labels:
        role: nodejs-k8s
    spec:
      containers:
        - name: nodejs-k8s
          image: lucabecci/node-k8s
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-k8s
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: nodejs-k8s