apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-k8s-loadbalancer
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nodejs-k8s-loadbalancer.k8s-test-nodejs.tk
    http:
      paths:
      - path: /
        backend:
          service:
            name: nodejs-k8s
            port: 
              number: 8080


#k8s-test-nodejs.tk domain test